### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by ggiannako** [flexi-framework/hopr#3]
Has anybody been able to build on a OS X machine? I get linking errors like the following while trying to build with both GNU and Intel compilers:

.
.
.
[ 98%] Building Fortran object CMakeFiles/hopr.dir/src/hopr.f90.o
ifort: command line remark #10382: option '-xHOST' setting '-xCORE-AVX2'
[100%] Linking Fortran executable bin/hopr
ifort: command line remark #10382: option '-xHOST' setting '-xCORE-AVX2'
Undefined symbols for architecture x86_64:
  "_mod_output_vars_mp_debugvisu_", referenced from:
      _mod_mesh_mp_fillmesh_ in libhoprlib.a(mesh.f90.o)
      _mod_output_mp_initoutput_ in libhoprlib.a(output.f90.o)
      _mod_output_hdf5_mp_spacefillingcurve_ in libhoprlib.a(output_hdf5.f90.o)
      _mod_sortijk_mp_sortelemsbycoords_ in libhoprlib.a(sortijk.f90.o)
.
.
.
.
.
ld: symbol(s) not found for architecture x86_64
make[2]: *** [bin/hopr] Error 1
make[1]: *** [CMakeFiles/hopr.dir/all] Error 2
make: *** [all] Error 2

Any suggestions?

**Comment by flexi-framework** [comment]
I cannot really help here, since there are no Mac users among the HOPR devs and we thus only support Linux at the moment. We would be happy though, if someone could contribute a patch adding Mac support.
Seems to me like CMake would try and build the the hoprlib for a different architecture. However I can't say what's the reason because we do not set any specific architecture flags.
